### ISSUE TITLE
Run femtocleaner

### ISSUE THREAD

**Issue by ararslan** [JuliaPackaging/BinaryProvider.jl#11] opened 2017-10-23 20:31 UTC
Please

**Comment by Keno** [comment] 2017-10-23 22:24
I think this repository kills femtocleaner. While processing this repo, it hung itself again. cc @KristofferC

**Comment by KristofferC** [comment] 2017-10-23 22:56
The problem is that the deprecation fixing of `PlatformEngines.jl` doesn't converge (it keeps trying to add a space) at a certain place. I'll try to make an MWE.

**Comment by KristofferC** [comment] 2017-10-24 12:40
```
julia> Deprecations.EXPR.buffer
"[i for i in 1:2 if all([c for c in a])]\n\n"

julia> Deprecations.EXPR
CSTParser.Generator  12:23 (12:23)
├─ CSTParser.IDENTIFIER  12:13 (12:12)
├─ CSTParser.KEYWORD{FOR::Tokenize.Tokens.Kind = 24}  14:17 (14:16)
└─ CSTParser.BinaryOpCall  18:23 (18:23)
   ├─ CSTParser.IDENTIFIER  18:19 (18:18)
   ├─ CSTParser.OPERATOR{6,IN::Tokenize.Tokens.Kind = 263,false}  20:22 (20:21)
   └─ CSTParser.IDENTIFIER  23:23 (23:23)

julia> body, fornode, iterand = Deprecations.children(Deprecations.EXPR);

julia> body.expr.val
c

julia> Deprecations.trailing_ws(body)
":"
```

That `trailing_ws` is pretty weird (should be a space). Seems like the spans are wrong.

**Comment by KristofferC** [comment] 2017-10-24 13:02
Probably fixed by https://github.com/ZacLN/CSTParser.jl/commit/e3c9d31edd51a9f508a2e24254fc5aaabadb319a?

I guess I should just upgrade Deprecations to newest CSTParser...

**Comment by KristofferC** [comment] 2017-11-06 20:35
https://github.com/JuliaPackaging/BinaryProvider.jl/pull/15

**Closed** 2017-11-06 20:41 UTC
